package server_board;


/**
* server_board/ServerBoard.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from server_board.idl
* Wednesday, May 10, 2006 9:27:16 PM AST
*/

public interface ServerBoard extends ServerBoardOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerBoard
