package server_board;

/**
* server_board/ServerBoardHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from server_board.idl
* Wednesday, May 10, 2006 9:27:16 PM AST
*/

public final class ServerBoardHolder implements org.omg.CORBA.portable.Streamable
{
  public server_board.ServerBoard value = null;

  public ServerBoardHolder ()
  {
  }

  public ServerBoardHolder (server_board.ServerBoard initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = server_board.ServerBoardHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    server_board.ServerBoardHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return server_board.ServerBoardHelper.type ();
  }

}
