package server_board;


/**
* server_board/ServerBoardHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from server_board.idl
* Wednesday, May 10, 2006 9:27:16 PM AST
*/

abstract public class ServerBoardHelper
{
  private static String  _id = "IDL:server_board/ServerBoard:1.0";

  public static void insert (org.omg.CORBA.Any a, server_board.ServerBoard that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static server_board.ServerBoard extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (server_board.ServerBoardHelper.id (), "ServerBoard");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static server_board.ServerBoard read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ServerBoardStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, server_board.ServerBoard value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static server_board.ServerBoard narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof server_board.ServerBoard)
      return (server_board.ServerBoard)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      server_board._ServerBoardStub stub = new server_board._ServerBoardStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
