package client_board;


/**
* client_board/ClientBoardOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from client_board.idl
* Wednesday, May 10, 2006 9:27:14 PM AST
*/

public interface ClientBoardOperations 
{
  String recieveMsg (String msg);
} // interface ClientBoardOperations
