package client_board;


/**
* client_board/ClientBoardHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from client_board.idl
* Wednesday, May 10, 2006 9:27:14 PM AST
*/

abstract public class ClientBoardHelper
{
  private static String  _id = "IDL:client_board/ClientBoard:1.0";

  public static void insert (org.omg.CORBA.Any a, client_board.ClientBoard that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static client_board.ClientBoard extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (client_board.ClientBoardHelper.id (), "ClientBoard");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static client_board.ClientBoard read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ClientBoardStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, client_board.ClientBoard value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static client_board.ClientBoard narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof client_board.ClientBoard)
      return (client_board.ClientBoard)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      client_board._ClientBoardStub stub = new client_board._ClientBoardStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
