package client_board;


/**
* client_board/ClientBoard.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from client_board.idl
* Wednesday, May 10, 2006 9:27:14 PM AST
*/

public interface ClientBoard extends ClientBoardOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientBoard
