package client_board;

/**
* client_board/ClientBoardHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from client_board.idl
* Wednesday, May 10, 2006 9:27:14 PM AST
*/

public final class ClientBoardHolder implements org.omg.CORBA.portable.Streamable
{
  public client_board.ClientBoard value = null;

  public ClientBoardHolder ()
  {
  }

  public ClientBoardHolder (client_board.ClientBoard initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = client_board.ClientBoardHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    client_board.ClientBoardHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return client_board.ClientBoardHelper.type ();
  }

}
