package client_side;

/**
* client_side/ClientSideHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from randclient.idl
* Sunday, May 14, 2006 9:02:39 PM AST
*/

public final class ClientSideHolder implements org.omg.CORBA.portable.Streamable
{
  public client_side.ClientSide value = null;

  public ClientSideHolder ()
  {
  }

  public ClientSideHolder (client_side.ClientSide initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = client_side.ClientSideHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    client_side.ClientSideHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return client_side.ClientSideHelper.type ();
  }

}
