package calc;


/**
* calc/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from E:/CORBA_CALC/calcServer/src/calcserver/calc.idl
* Wednesday, May 10, 2006 3:58:17 AM AST
*/

public interface CalcOperations 
{
  float calc (int op, float param1, float param2);
} // interface CalcOperations
