package calc;


/**
* calc/_CalcStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from E:/CORBA_CALC/calcServer/src/calcserver/calc.idl
* Wednesday, May 10, 2006 3:58:17 AM AST
*/

public class _CalcStub extends org.omg.CORBA.portable.ObjectImpl implements calc.Calc
{

  public float calc (int op, float param1, float param2)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("calc", true);
                $out.write_long (op);
                $out.write_float (param1);
                $out.write_float (param2);
                $in = _invoke ($out);
                float $result = $in.read_float ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return calc (op, param1, param2        );
            } finally {
                _releaseReply ($in);
            }
  } // calc

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:calc/Calc:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _CalcStub
