package calc;


/**
* calc/Calc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from E:/CORBA_CALC/calcServer/src/calcserver/calc.idl
* Wednesday, May 10, 2006 3:58:17 AM AST
*/

public interface Calc extends CalcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calc
