package calc;

/**
* calc/CalcHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from E:/CORBA_CALC/calcServer/src/calcserver/calc.idl
* Wednesday, May 10, 2006 3:58:17 AM AST
*/

public final class CalcHolder implements org.omg.CORBA.portable.Streamable
{
  public calc.Calc value = null;

  public CalcHolder ()
  {
  }

  public CalcHolder (calc.Calc initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = calc.CalcHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    calc.CalcHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return calc.CalcHelper.type ();
  }

}
