package server_side;

/**
* server_side/ServerSideHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from rand.idl
* Wednesday, May 10, 2006 11:48:36 PM AST
*/

public final class ServerSideHolder implements org.omg.CORBA.portable.Streamable
{
  public server_side.ServerSide value = null;

  public ServerSideHolder ()
  {
  }

  public ServerSideHolder (server_side.ServerSide initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = server_side.ServerSideHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    server_side.ServerSideHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return server_side.ServerSideHelper.type ();
  }

}
