package server_side;


/**
* server_side/ServerSide.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from rand.idl
* Wednesday, May 10, 2006 11:48:36 PM AST
*/

public interface ServerSide extends ServerSideOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerSide
