package client_side;


/**
* client_side/ClientSideHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from randclient.idl
* Sunday, May 14, 2006 9:02:39 PM AST
*/

abstract public class ClientSideHelper
{
  private static String  _id = "IDL:client_side/ClientSide:1.0";

  public static void insert (org.omg.CORBA.Any a, client_side.ClientSide that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static client_side.ClientSide extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (client_side.ClientSideHelper.id (), "ClientSide");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static client_side.ClientSide read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ClientSideStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, client_side.ClientSide value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static client_side.ClientSide narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof client_side.ClientSide)
      return (client_side.ClientSide)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      client_side._ClientSideStub stub = new client_side._ClientSideStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
