package server_board;


/**
* server_board/ServerBoardOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from server_board.idl
* Wednesday, May 10, 2006 9:27:16 PM AST
*/

public interface ServerBoardOperations 
{
  String connect (String nickName);
  String disconnect (String nickName);
  String recieveMsg (String nickName, String msg);
} // interface ServerBoardOperations
